### PR TITLE
Update for using new std::io

### PR DESCRIPTION
**Pull request by snf**
Didn't get why do you need USER_RWX permissions. But everything is working

### CODE REVIEW

**Comment by KokaKiwi** [comment]
The crate `gxx` I wrote was just a "copy" of the `gcc` crate, with basically just `CC` env var replaced by `CXX` var, and the USER_RWX flag was in the `gcc` crate at the time I wrote this.

**Comment by KokaKiwi** [comment]
Oh and, actually I'm rewriting the entire library (in fact, I'm rewriting my bindings generator which is used for generating this lib), and I also updated `gxx` and `llvm-config` crates too, so I'll merge your changes (which apparently use the new I/O Rust libs) with mine.

**Comment by snf** [comment]
Are you changing the python class representation? I'm adding more APIs right now.

**Comment by KokaKiwi** [comment]
Yep, but the changes won't be too "big" as I'm satisfied with the actual way to represent the C++ API.
Actually, the "big" changes I made is how enums are defined (using the `enum` module of Python) and how Option is handled.
But you can still add more APIs if you want, I'll convert them if they need to. :)

**Comment by snf** [comment]
Good to know, will keep working on this then.

**Pull request merged**
